import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvide from "@/provider/sessionProvide";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvide>

        {children}
        </NextAuthProvide>
        </body>
    </html>
  );
}
